name: CI

on:
  push:
    branches:
    - main
  release:
    types: [published]
  pull_request:
    branches:
    - main

env:
    SOLUTION: 'Rowbot.sln'
    TRIGGER_EVENT_NAME: ${{ github.event_name }}

jobs:
  print_trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Print trigger name
      run: echo "TRIGGER_EVENT_NAME $TRIGGER_EVENT_NAME"
    
  run_tests:
  
    runs-on: ubuntu-latest

    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Execute unit tests
      run: dotnet test
      
  deploy_to_nuget:
    if: '$TRIGGER_EVENT_NAME' == 'release'
    needs: [run_tests]
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.ref_name }}

    steps:
    - name: Print version
      run: echo "RELEASE_VERSION $RELEASE_VERSION"

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with version
      run: dotnet build $SOLUTION --configuration Release -p:Version=$RELEASE_VERSION
      
    - name: Publish to nuget
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
