name: CI

on:
  push:
    branches:
    - main
  release:
    types: [published]
  pull_request:
    branches:
    - main

env:
    SOLUTION: 'Rowbot.sln'

jobs:
  print_trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Print trigger name
      run: echo ${{ github.event_name }}
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Output Ref Name
      run: echo ${{ github.ref_name }}

  run_tests:
  
    runs-on: ubuntu-latest

    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Execute unit tests
      run: dotnet test
      
  deploy_to_nuget:
    if: ${{ github.event_name }} == 'release'
    needs: [run_tests]
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.ref_name }}

    steps:
    - name: Print version
      run: echo "RELEASE_VERSION $RELEASE_VERSION"

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with version
      run: dotnet build $SOLUTION --configuration Release -p:Version=$RELEASE_VERSION
      
    - name: Publish to nuget
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
